from re import S
import turtle
avery = turtle.Pen()
kate = turtle.Pen()

avery.forward(50)
avery.right(90)
avery.forward(20)

kate.left(90)
kate.forward(100)

jacob = turtle.Pen()
jacob.left(180)
jacob.forward(80)

val = input("Hit enter for turtle pitchfork")

avery.reset()
kate.reset()
jacob.reset()

# yuri = turtle.Pen()
# natsuki = turtle.Pen()
# sayori = turtle.Pen()
Just_Monika =turtle.Pen()

# Just_Monika.right(90)
# sayori.right(90)
# natsuki.right(90)
# yuri.right(90)
# yuri.forward(100)
# yuri.left(90)
# yuri.forward(40)
# yuri.right(90)
# yuri.forward(50)
# natsuki.forward(100)
# natsuki.right(90)
# natsuki.forward(40)
# natsuki.left(90)
# natsuki.forward(50)
# sayori.forward(120)
# sayori.left(90)
# sayori.forward(30)
# sayori.right(90)
# sayori.forward(25)
# Just_Monika.forward(120)
# Just_Monika.right(90)
# Just_Monika.forward(30)
# Just_Monika.left(90)
# Just_Monika.forward(25)

avery.forward(100)
avery.left(90)
avery.forward(40)
avery.right(90)
avery.forward(50)
kate.forward(100)
kate.right(90)
kate.forward(40)
kate.left(90)
kate.forward(50)
jacob.forward(120)
jacob.left(90)
jacob.forward(30)
jacob.right(90)
jacob.forward(25)
Just_Monika.forward(120)
Just_Monika.right(90)
Just_Monika.forward(30)
Just_Monika.left(90)
Just_Monika.forward(25)
val = input("Hit enter to end program")